### ISSUE TITLE
Family Config: Nova EG

### ISSUE THREAD

**Issue by Fearless-one** [RoyaleAPI/cr-api#169]
## Request Details:

```
GET
http://api.cr-api.com/top/clans
```

## Response Details:

```
Code: 200

[...]

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
 2. Expected behaviour: 
 3. Console logs (if applicable): 
 4. Screenshots (if applicable):

**Comment by selfish** [comment]
This bug report is lacking detail, and I don't understand what the issue is.
I'm closing it. If you decide to explain the issue, reopen it.

**Comment by smlbiobot** [comment]
@selfish he DMs me and he just doesn’t know what to type lol

anyway @Fearless-one you gave me a bunch of emoji in family description but atm it’s not possible to support them in YAML.

This is what I managed to do so far. We can look into enabling emojis later:

```yaml
  - name: Nova EG
    key: novaeg
    color: purple
    emblem: Star_Shine_03
    sort: trophy
    feature: true
    tracK: false
    info:
      description: >
        Official Nova eSports & CWA Clan|EG|Taurus|Lyra|Phoenix|Draco|
        Corona|Pegasus|Hydra|Octans|Aquila|Cygnus
      social:
        - discord: http://discord.gg/hYAZNTF
    clans:
      - name: Nova EG Cygnus
        tag: 8CRQRVJQ
      - name: Nova EG Taurus
        tag: 8J9QP82G
      - name: Nova EG Octans
        tag: 8UPGJ8LC
      - name: Nova EG Phoenix
        tag: 8VCUJU2C
      - name: Nova EG Hydra
        tag: 9PPRR8JC
      - name: Nova EG Lyra
        tag: 8U99P0Q8
      - name: Nova EG Draco
        tag: 8VJQPUC2
      - name: Nova EG Corona
        tag: 8JV9LVUL
      - name: Nova EG Pegasus
        tag: 990V0LJ8
      - name: Nova EG Aquila
        tag: 9Q9R9VCJ
```
