### ISSUE TITLE
One`S Team family

### ISSUE THREAD

**Issue by Anton3** [RoyaleAPI/cr-api#425]
```yaml
name: One`S Team
key: onesteam
color: black
emblem: Flame_04
sort: trophy
info:
  logo: https://psv4.userapi.com/c848224/u169252871/docs/d16/086e59595922/Untitled-1.jpg?extra=jU2Dy--a7jFZ7Sfd0Fhl00vdY6Ggf2KzyM6WNRpMLUD27EX9Fs4siKyeUmpoGQ0m48jy4M1S5gvRMygkrOGhvgu4rAzCqj6nNMx-MlXycIx92ShmWqq1uKr73d7Ye1lMq_Iv2mD4u_MK
  description: >
    One`S Team - клан, который никогда не сдается и вот уже который год уверенно
    поднимается вверх топа РФ. Эта семья родилась на Twitch TV во время стримов,
    закалилась временем и выросла в достойных игроков, которые ни раз проявили
    себя в различных турнирах, занимая первые места! Один за всех и все за одного!
  social:
    - youtube: https://www.youtube.com/channel/UCZln4Lht13nrnHS92WlfjnQ
    - twitch: https://www.twitch.tv/ones_channel
clans:
  - name: One`S Team
    tag: 8QG0JCVY
  - name: Психушка
    tag: 9JRGCQGP
```
