### ISSUE TITLE
Pantheon Family - UPDATE

### ISSUE THREAD

**Issue by PantheonFlint** [RoyaleAPI/cr-api#426]
Update to existing family, Pantheon. Changes:
- Removed 1 clan
- Modified description

YML below.

```yaml
name: Pantheon Family
key: Pantheon
color: red
track: true
emblem: Flame_03
feature: true
vip: true
info:
  logo: /static/img/brands/logo/Pantheon.png
  description: >
    __PANTHEON__ is a family of 9 clans that are made up of over 400 members from around the world. 
    We accept players of all skill and competitive levels.
  social:
    - twitter: http://twitter.com/PantheonFamily1
    - discord: https://discord.gg/x6N9cVR
    - website: http://pantheonfamily.com
clans:
  - name: ARES
    tag: 92LVUPJP
  - name: ATLAS
    tag: 8YLY2RV2
  - name: CHRONOS
    tag: 8U0PQCR0
  - name: HADES
    tag: 90GCRGY2
  - name: HYPERION
    tag: 8R92C8VC
  - name: KRATOS
    tag: 9LVV9VVV
  - name: NEMESIS
    tag: 8QVYQL02
  - name: POSEIDON
    tag: 9R99Y9CU
  - name: STYX
    tag: 9Y20CQ9Y
```
